plugins {
    id 'java-library'

    id 'idea'

    // see https://fabricmc.net/develop for new versions
    id 'net.fabricmc.fabric-loom-remap' version '1.16-SNAPSHOT' apply false

    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.144' apply false
}

println("> Executing inside the root project.")

def parsed_java_version = Integer.parseInt(project.java_version)

allprojects {
    // The version tag. Should follow the Semantic Versioning (SemVer) system
    // with the Minecraft version suffix (e.g. major.minor.patch+minecraft_version)
    version = "${project.mod_version}+${project.minecraft_version}"

    // The publisher id. Must follow the standard Java package reverse-domain naming convention (e.g. com.example)
    group = project.maven_group
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'idea'

    java {
        // Generates source code file which ends with -sources.jar
        withSourcesJar()

        // Sets the Java version
        toolchain.languageVersion = JavaLanguageVersion.of(parsed_java_version)
    }

    tasks.withType(JavaCompile).configureEach {
        // Ensures that the Java version is set correctly
        it.options.release = parsed_java_version

        // Ensures that the encoding is set to UTF-8
        it.options.encoding = charset
    }
}
