# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
minecraft_version=26.1
loader_version=0.18.5
fabric_api_version=0.144.3
#yarn_build=4
# Mod Menu Properties
mod_menu_version=18.0.0-alpha.8
# Mod Properties
mod_version=1.1.0
maven_group=chorus
archives_base_name=simple-tracking-compass

# Recommended Fabric Properties Here: https://modmuss50.me/fabric.html
# All Yarn Builds Here: https://maven.fabricmc.net/net/fabricmc/yarn/
# All ModMenu Versions Here: https://mvnrepository.com/artifact/com.terraformersmc/modmenu