# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.debug=false

# Java
java_version=25
charset=UTF-8

# Minecraft
minecraft_version=26.1

# Common
mod_version=1.2.0
mod_name=Simple Tracking Compass
archives_base_name=simple-tracking-compass
maven_group=net.chorus
mod_id=simpletrackingcompass
description=Simple Tracking Compass is a Minecraft mod that adds a Compass to the top-left corner of your screen which lets you track other players.

# Fabric (https://modmuss50.me/fabric.html)
fabric_version=0.18.6
fabric_api_version=0.145.1
mod_menu_version=18.0.0

# NeoForge (https://neoforged.net)
neo_version=26.1.0.19-beta
