modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/ChorusFruuuit/SimpleTrackingCompass/issues"

[[mods]]
modId="simpletrackingcompass"
version="${mod_version}"
displayName="Simple Tracking Compass"
displayURL="https://github.com/ChorusFruuuit/SimpleTrackingCompass"
iconFile="icon.png"
bannerFile="icon.png"
authors="Chorus_Fruuu1t"
description="${description}"

[[mixins]]
config="simpletrackingcompass.mixins.json"

[[dependencies.simpletrackingcompass]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.simpletrackingcompass]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
